QUESTIONS = [
    {
        'number': 1,
        'title': 'Assalomu alaykum!',
        'text': 'Biz odamlarning kundalik hayotida uchraydigan muammolarni o\'rganish maqsadida qisqa anonim so\'rovnoma tayyorladik.',
        'subtext': 'So\'rovnomani to\'ldirish taxminan 5–10 daqiqa vaqt oladi. Sizning javoblaringiz kelajakda odamlar hayotini osonlashtiradigan foydali loyiha yoki xizmat yaratishda muhim ahamiyatga ega bo\'ladi.',
        'type': 'consent',
    },
    {
        'number': 2,
        'title': 'Ismingiz (ixtiyoriy)',
        'text': 'Ismingizni kiriting (majburiy emas)',
        'type': 'text',
        'max_length': 50,
        'required': False,
    },
    {
        'number': 3,
        'title': 'Qaysi viloyatda yashaysiz?',
        'text': 'Yashash joyingizni tanlang',
        'type': 'select',
        'required': True,
        'options': [
            'Andijon', 'Namangan', 'Farg\'ona', 'Toshkent shahri',
            'Toshkent viloyati', 'Samarqand', 'Buxoro', 'Navoiy',
            'Jizzax', 'Sirdaryo', 'Qashqadaryo', 'Surxondaryo',
            'Xorazm', 'Qoraqalpog\'iston Respublikasi',
        ],
    },
    {
        'number': 4,
        'title': 'Yoshingiz nechada?',
        'text': 'Yoshingizni kiriting',
        'type': 'number',
        'required': True,
        'min': 10,
        'max': 100,
    },
    {
        'number': 5,
        'title': 'Quyidagi muammolardan qaysilariga tez-tez duch kelasiz?',
        'text': 'Bir nechta javobni tanlash mumkin',
        'type': 'checkbox',
        'required': True,
        'options': [
            '💼 Ish topish', '🔧 Usta topish', '👨‍⚕️ Doktor qabuliga yozilish',
            '⏰ Navbat kutish', '🌐 Internet sifati', '🚗 Transport',
            '📚 Ta\'lim', '🏛️ Davlat xizmatlari', '💳 Onlayn to\'lovlar',
            '📄 Hujjat ishlari', '💭 Boshqa',
        ],
        'has_other': True,
    },
    {
        'number': 6,
        'title': 'Bir kun davomida eng ko\'p vaqtingiz nimaga ketadi?',
        'text': 'Bir nechta javobni tanlash mumkin',
        'type': 'checkbox',
        'required': True,
        'options': ['💼 Ish', '📚 O\'qish', '🚗 Transport', '⏰ Navbat kutish', '📱 Telefon', '🏠 Uy ishlari', '💭 Boshqa'],
        'has_other': True,
    },
    {
        'number': 7,
        'title': 'Quyidagi ishlarning qaysi birini web-sayt yoki Telegram bot orqali osonroq qilishni xohlardingiz?',
        'text': 'Bir nechta javobni tanlash mumkin',
        'type': 'checkbox',
        'required': True,
        'options': ['🛒 Mahsulot yoki oziq-ovqat buyurtma qilish', '🏥 Shifokorga navbat olish', '💇 Sartarosh yoki go\'zallik saloniga yozilish', '🔧 Usta topish', '🚕 Taksi yoki transport topish', '🏠 Uy yoki kvartira topish', '💼 Ish topish', '📚 Kurs yoki repetitor topish', '🛍️ Chegirmalarni topish', '🍽️ Restoran/kafe topish va buyurtma qilish', '📦 Kuryer yoki yetkazib berish xizmatlari', '🏛️ Davlat xizmatlaridan foydalanish', '💳 To\'lovlarni amalga oshirish', '📄 Hujjatlarni rasmiylashtirish', '🏪 Yaqin atrofdagi do\'kon va xizmatlarni topish', '💭 Boshqa'],
        'has_other': True,
    },
    {
        'number': 8,
        'title': 'Siz yashaydigan hududda qaysi onlayn xizmat bo\'lsa, odamlar uchun foydali bo\'lardi?',
        'text': 'Bir nechta javobni tanlash mumkin',
        'type': 'checkbox',
        'required': True,
        'options': ['📍 Hududdagi barcha xizmatlar bitta joyda', '🛒 Mahalliy do\'konlar va mahsulotlar katalogi', '🏷️ Chegirmalar va aksiyalar haqida xabar berish', '🔧 Ishonchli ustalar katalogi', '👨‍⚕️ Shifokorlar va klinikalar katalogi', '💼 Mahalliy ish o\'rinlari', '🏠 Uy-joy ijarasi yoki sotib olish', '🚗 Mashina sotish va olish', '📦 Mahalliy yetkazib berish xizmati', '🏫 O\'quv markazlari va repetitorlar', '🍔 Kafelar va restoranlar', '🛍️ Mahalliy xizmatlar va do\'konlar', '📰 Hudud yangiliklari va e\'lonlari', '🤝 Ishonchli xizmat ko\'rsatuvchilarni topish', '❌ Menimcha, bunday xizmat kerak emas', '💭 Boshqa'],
        'has_other': True,
    },
    {
        'number': 9,
        'title': 'Kerakli mahsulot yoki xizmatni topish uchun odatda qayerdan foydalanasiz?',
        'text': 'Bir nechta javobni tanlash mumkin',
        'type': 'checkbox',
        'required': True,
        'options': ['🔍 Google yoki Yandex\'dan qidiraman', '📱 Telegram guruhlaridan qidiraman', '📸 Instagram\'dan qidiraman', '👥 Tanishlarimdan so\'rayman', '🗺️ Yandex Maps yoki Google Maps\'dan foydalanaman', '🏃 O\'zim borib qidiraman', '📞 Telefon qilib so\'rayman', '❌ Odatda topa olmayman', '💭 Boshqa'],
        'has_other': True,
    },
    {
        'number': 10,
        'title': 'Agar sizga qulay web-sayt yoki Telegram bot yaratilsa, qaysi xizmatdan foydalanardingiz?',
        'text': 'Bir nechta javobni tanlash mumkin',
        'type': 'checkbox',
        'required': True,
        'options': ['🛒 Mahsulot buyurtma qilish', '🏷️ Chegirmalarni topish', '🔧 Usta topish', '💼 Ish topish', '🏥 Shifokorga yozilish', '🏠 Uy topish', '🚗 Mashina topish', '📚 Kurs/repetitor topish', '🍽️ Restoran va kafelarni topish', '📦 Yetkazib berish', '🏪 Mahalliy do\'konlarni topish', '📍 Yaqin atrofdagi xizmatlarni topish', '📅 Navbatga yozilish', '📰 E\'lonlar joylash', '🤖 Telegram bot orqali turli xizmatlardan foydalanish', '❌ Hech qaysi biri'],
    },
    {
        'number': 11,
        'title': 'Sizga yangi onlayn xizmat qaysi ko\'rinishda qulayroq bo\'lardi?',
        'text': 'Variantlardan bittasini tanlang',
        'type': 'checkbox',
        'required': True,
        'options': ['🤖 Telegram bot', '🌐 Web-sayt', '📱 Mobil ilova', '📱 Telegram kanal', '📞 Telefon orqali', '🤷 Farqi yo\'q, qulay bo\'lsa bo\'ldi'],
    },
    {
        'number': 12,
        'title': 'Yangi web-sayt yoki Telegram botdan foydalanishingiz uchun unda nima bo\'lishi kerak?',
        'text': 'Bir nechta javobni tanlash mumkin',
        'type': 'checkbox',
        'required': True,
        'options': ['⚡ Foydalanish juda oson bo\'lishi', '🆓 Bepul bo\'lishi', '📍 Menga yaqin xizmatlarni ko\'rsatishi', '💰 Arzon narxlar yoki chegirmalar bo\'lishi', '⏱️ Vaqtimni tejashi', '🔒 Ishonchli bo\'lishi', '📞 Telefon qilishga hojat qoldirmasligi', '🚚 Yetkazib berish imkoniyati', '🔔 Kerakli xabarlarni yuborishi', '💳 Onlayn to\'lov qilish imkoniyati', '⭐ Reyting va sharhlar bo\'lishi', '🤖 Telegram orqali ishlashi', '💭 Boshqa'],
        'has_other': True,
    },
    {
        'number': 13,
        'title': 'Quyidagi ishlarning qaysi birini avtomatik qilish foydali bo\'lardi?',
        'text': 'Bir nechta javobni tanlash mumkin',
        'type': 'checkbox',
        'required': True,
        'options': ['📅 Navbatga avtomatik yozilish', '🔔 Chegirmalar haqida xabar olish', '💼 Yangi ishlar haqida xabar olish', '🏷️ Mahsulot narxi tushganda xabar olish', '🏥 Shifokor qabuliga yozilish', '🔧 Usta topish', '📦 Buyurtmani kuzatish', '💳 To\'lovlarni amalga oshirish', '📍 Yaqin xizmatlarni topish', '🏠 Uy narxlari va ijaralarni kuzatish','📚 Kurslar haqida xabar olish', '🤖 Telegram bot orqali avtomatik xizmatlardan foydalanish', '💭 Boshqa'],
        'has_other': True,
    },
    {
        'number': 14,
        'title': 'Agar hozir siz uchun bitta yangi web-sayt yoki Telegram bot yaratilsa, qaysi birini tanlagan bo\'lardingiz?',
        'text': 'Bir nechta javobni tanlash mumkin',
        'type': 'checkbox',
        'required': True,
        'options': ['🏷️ Mening hududimdagi chegirmalarni ko\'rsatadigan xizmat', '🔧 Ishonchli usta topish xizmati', '💼 Ish topish platformasi', '🏥 Shifokor va klinika topish xizmati', '🛒 Mahsulotlarni solishtirish xizmati', '🏠 Uy-joy topish xizmati', '🚗 Mashina topish/sotish xizmati', '📚 Kurs va repetitor topish xizmati', '📦 Yetkazib berish xizmati', '🍽️ Kafe va restoranlarni topish xizmati', '📍 Mahalliy xizmatlar katalogi', '📰 Hududdagi e\'lonlar platformasi', '🤖 Hamma xizmatlar bitta Telegram botda', '🌐 Hamma xizmatlar bitta saytda', '💭 Boshqa'],
        'has_other': True,
    },
    {
        'number': 15,
        'title': 'Agar sizga kerak bo\'lgan shunday xizmat yaratilsa, undan foydalanarmidingiz??',
        'type': 'select',
        'required': True,
        'options': [
            {'label': '🔥 Ha, har kuni'},
            {'label': '👍 Ha, tez-tez'},
            {'label': '🙂 Ba\'zida'},
            {'label': '🤔 Faqat kerak bo\'lganda'},
            {'label': '❌ Yo\'q'},
        ],
    },
]

TOTAL_QUESTIONS = len(QUESTIONS)
