QUESTIONS = [
    {
        'number': 1,
        'title': 'Assalomu alaykum!',
        'text': 'Biz odamlarning kundalik hayotida uchraydigan muammolarni o\'rganish maqsadida qisqa anonim so\'rovnoma tayyorladik.',
        'subtext': 'So\'rovnomani to\'ldirish taxminan 5–10 daqiqa vaqt oladi. Sizning javoblaringiz kelajakda odamlar hayotini osonlashtiradigan foydali loyiha yoki xizmat yaratishda muhim ahamiyatga ega bo\'ladi.',
        'type': 'consent',
    },
    {
        'number': 2,
        'title': 'Ismingiz (ixtiyoriy)',
        'text': 'Ismingizni kiriting (majburiy emas)',
        'type': 'text',
        'max_length': 50,
        'required': False,
    },
    {
        'number': 3,
        'title': 'Qaysi viloyatda yashaysiz?',
        'text': 'Yashash joyingizni tanlang',
        'type': 'select',
        'required': True,
        'options': [
            'Andijon', 'Namangan', 'Farg\'ona', 'Toshkent shahri',
            'Toshkent viloyati', 'Samarqand', 'Buxoro', 'Navoiy',
            'Jizzax', 'Sirdaryo', 'Qashqadaryo', 'Surxondaryo',
            'Xorazm', 'Qoraqalpog\'iston Respublikasi',
        ],
    },
    {
        'number': 4,
        'title': 'Yoshingiz nechada?',
        'text': 'Yoshingizni kiriting',
        'type': 'number',
        'required': True,
        'min': 10,
        'max': 100,
    },
    {
        'number': 5,
        'title': 'Quyidagi muammolardan qaysilariga tez-tez duch kelasiz?',
        'text': 'Bir nechta javobni tanlash mumkin',
        'type': 'checkbox',
        'required': True,
        'options': [
            'Ish topish', 'Usta topish', 'Doktor qabuliga yozilish',
            'Navbat kutish', 'Internet sifati', 'Transport',
            'Ta\'lim', 'Davlat xizmatlari', 'Onlayn to\'lovlar',
            'Hujjat ishlari', 'Boshqa',
        ],
        'has_other': True,
    },
    {
        'number': 6,
        'title': 'Bir kun davomida eng ko\'p vaqtingiz nimaga ketadi?',
        'text': 'Bir nechta javobni tanlash mumkin',
        'type': 'checkbox',
        'required': True,
        'options': ['Ish', 'O\'qish', 'Transport', 'Navbat kutish', 'Telefon', 'Uy ishlari', 'Boshqa'],
        'has_other': True,
    },
    {
        'number': 7,
        'title': 'Qaysi ishni telefon orqali bajarishni xohlardingiz, lekin hozir buning qulay usuli yo\'q?',
        'text': 'Fikringizni yozing',
        'type': 'textarea',
        'max_length': 1000,
        'required': True,
    },
    {
        'number': 8,
        'title': 'Sizningcha, O\'zbekistonda hali mavjud bo\'lmagan, lekin juda kerak bo\'lgan ilova yoki xizmat qanday bo\'lishi kerak?',
        'text': 'Fikringizni batafsil yozing',
        'type': 'textarea',
        'max_length': 1000,
        'required': True,
    },
    {
        'number': 9,
        'title': 'Oxirgi bir oy ichida sizni eng ko\'p nima asabiylashtirdi?',
        'text': 'Bir nechta javobni tanlash mumkin',
        'type': 'checkbox',
        'required': True,
        'options': ['Internet', 'Navbat', 'Ish', 'Transport', 'Davlat xizmatlari', 'Narxlar', 'Boshqa'],
        'has_other': True,
    },
    {
        'number': 10,
        'title': 'Agar bitta muammoni butunlay yo\'q qila olsangiz, qaysi muammoni tanlardingiz?',
        'text': 'Fikringizni yozing',
        'type': 'textarea',
        'max_length': 1000,
        'required': True,
    },
    {
        'number': 11,
        'title': 'Quyidagi ilovalardan qaysilaridan tez-tez foydalanasiz?',
        'text': 'Bir nechta javobni tanlash mumkin',
        'type': 'checkbox',
        'required': True,
        'options': ['Telegram', 'Instagram', 'Click', 'Payme', 'Yandex Go', 'Uzum', 'YouTube', 'Boshqa'],
        'has_other': True,
    },
    {
        'number': 12,
        'title': 'Siz ishlatadigan ilovalarda sizga eng yoqmaydigan narsa nima?',
        'text': 'Fikringizni batafsil yozing',
        'type': 'textarea',
        'max_length': 1000,
        'required': True,
    },
    {
        'number': 13,
        'title': 'Qaysi ilova yoki xizmat yaratilsa, uni darhol telefoningizga o\'rnatar edingiz?',
        'text': 'Fikringizni yozing',
        'type': 'textarea',
        'max_length': 1000,
        'required': True,
    },
    {
        'number': 14,
        'title': 'Sizni har kuni eng ko\'p qiynaydigan muammo nima?',
        'text': 'Uni iloji boricha batafsil yozing',
        'type': 'textarea',
        'max_length': 2000,
        'required': True,
    },
    {
        'number': 15,
        'title': 'Ushbu muammo sizni qanchalik bezovta qiladi?',
        'text': 'Bezovtalik darajasini tanlang',
        'type': 'rating',
        'required': True,
        'options': [
            {'value': 1, 'label': 'Juda kam'},
            {'value': 2, 'label': 'Kam'},
            {'value': 3, 'label': 'O\'rtacha'},
            {'value': 4, 'label': 'Kuchli'},
            {'value': 5, 'label': 'Juda kuchli'},
        ],
    },
]

TOTAL_QUESTIONS = len(QUESTIONS)
