# Generated by Django 5.2.13 on 2026-07-05 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP manzil')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Tugatilgan vaqt')),
            ],
            options={
                'verbose_name': 'IP log',
                'verbose_name_plural': 'IP loglari',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ism')),
                ('region', models.CharField(max_length=50, verbose_name='Viloyat')),
                ('age', models.IntegerField(verbose_name='Yosh')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP manzil')),
                ('user_agent', models.TextField(blank=True, verbose_name='Qurilma')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
            ],
            options={
                'verbose_name': 'Respondent',
                'verbose_name_plural': 'Respondentlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(verbose_name='Savol raqami')),
                ('answer', models.TextField(verbose_name='Javob')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Saqlangan vaqt')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.response', verbose_name='Respondent')),
            ],
            options={
                'verbose_name': 'Javob',
                'verbose_name_plural': 'Javoblar',
                'ordering': ['question_number'],
            },
        ),
    ]
